//! The committed test Entitlement Schedule (`tests/fixtures/test_schedule.ghes`, generated by
//! `issuer/crates/service/tests/fixture_gen.rs`) and its test signing key.

use ed25519_dalek::{Signer as _, SigningKey};
use ghost_entitlement::schedule::ScheduleContent;
use ghost_entitlement::Schedule;
use sha2::{Digest, Sha256};

/// First access week of the test schedule (Monday 2026-09-07) and its length.
pub const FIRST_WEEK: u64 = 2957;
pub const WEEKS: u64 = 26;

pub const FIXTURE: &[u8] = include_bytes!("../fixtures/test_schedule.ghes");

/// The test schedule key: Ed25519 from SHA-256("ghost/test/schedule-key"). Test schedules only.
pub fn signing_key() -> SigningKey {
    SigningKey::from_bytes(&Sha256::digest(b"ghost/test/schedule-key").into())
}

pub fn schedule_key() -> [u8; 32] {
    signing_key().verifying_key().to_bytes()
}

pub fn schedule() -> Schedule {
    Schedule::verify_with_key(FIXTURE, &schedule_key()).unwrap()
}

/// Encodes `content` and signs it with the test key.
pub fn resign(content: &ScheduleContent) -> Vec<u8> {
    resign_body(&content.body().unwrap())
}

/// Signs raw body bytes with the test key (for edits the encoder cannot express).
pub fn resign_body(body: &[u8]) -> Vec<u8> {
    let msg = [ghost_entitlement::schedule::SIGNATURE_DOMAIN, body].concat();
    [body, &signing_key().sign(&msg).to_bytes()].concat()
}
