//! Regenerates the committed entitlement test fixtures. Both tests are ignored; run them only to
//! rebuild the fixtures, in release mode:
//!
//!   cargo test --release -p ghost-issuer --test fixture_gen -- --ignored generate_test_schedule
//!   GHOST_VECTOR_OUT=<file> cargo test --release -p ghost-issuer --test fixture_gen -- --ignored generate_ghost_vectors
//!
//! `generate_test_schedule` creates fresh RSA-2048 keys (so every later vector changes with it);
//! `generate_ghost_vectors` is deterministic in the committed fixtures and writes the `[ghost]`
//! section of `protocol/test-vectors/blind_rsa_pp2.txt`.

mod common;

use std::fmt::Write as _;

use common::fixture::{self, FIRST_WEEK, WEEKS};
use ed25519_dalek::Signer as _;
use ghost_entitlement::batch::{self, Layout, Position};
use ghost_entitlement::challenge::{redemption_context, TokenChallenge};
use ghost_entitlement::grid::{credit_epoch, invite_epoch, price_epoch, Kind};
use ghost_entitlement::monero::MoneroNetwork;
use ghost_entitlement::onion::Onion;
use ghost_entitlement::schedule::{Constants, KeyContent, PriceEntry, ScheduleContent, SlotEntry};
use ghost_entitlement::token::{self, AUTHENTICATOR_LEN};
use ghost_entitlement::{Expect, Schedule};
use ghost_issuer::signer::{CheckedSigner, ReferenceSigner, Signer};
use sha2::{Digest, Sha256};

pub const ISSUER_NAME: &str = "ghost-issuer-test";

fn test_onion(label: &str, port: u16) -> String {
    Onion {
        pubkey: Sha256::digest(label.as_bytes()).into(),
        port,
    }
    .format()
}

fn key_list() -> Vec<(Kind, u64)> {
    let weeks = FIRST_WEEK..FIRST_WEEK + WEEKS;
    let mut keys: Vec<(Kind, u64)> = weeks.clone().map(|w| (Kind::Access, w)).collect();
    let mut invites: Vec<u64> = weeks.clone().map(invite_epoch).collect();
    invites.dedup();
    let mut credits: Vec<u64> = weeks.map(credit_epoch).collect();
    credits.dedup();
    keys.extend(invites.into_iter().map(|e| (Kind::Invite, e)));
    keys.extend(credits.into_iter().map(|e| (Kind::Credit, e)));
    keys
}

#[test]
#[ignore = "regenerates tests/fixtures of ghost-entitlement with fresh keys"]
fn generate_test_schedule() {
    let mut keys = Vec::new();
    let mut key_file = String::from(
        "# Test-only private keys of test_schedule.ghes: <kind byte> <epoch> <PKCS #8 DER hex>.\n\
         # Generated by issuer/crates/service/tests/fixture_gen.rs; never loaded by production code.\n",
    );
    for (kind, epoch) in key_list() {
        let signer = ReferenceSigner::generate(kind, epoch).unwrap();
        let pk = signer.public_key().clone();
        let der = signer.to_pkcs8_der().unwrap();
        let checked = CheckedSigner::new(signer, pk.clone()).unwrap();
        let challenges = ghost_blind_rsa::permutation_proof_challenges(&pk).unwrap();
        let proof = challenges.map(|c| checked.blind_sign(&c).unwrap());
        ghost_blind_rsa::verify_permutation_proof(&pk, &proof).unwrap();
        keys.push(KeyContent {
            kind,
            epoch,
            spki: pk.to_spki(),
            proof,
        });
        writeln!(key_file, "{} {} {}", kind.byte(), epoch, hex::encode(der)).unwrap();
    }
    let last = FIRST_WEEK + WEEKS - 1;
    let prices = (price_epoch(FIRST_WEEK)..=price_epoch(last))
        .enumerate()
        .map(|(i, e)| PriceEntry {
            price_epoch: e,
            pack_price_atomic: 200_000_000_000 + 50_000_000_000 * (i as u64 / 2),
        })
        .collect();
    let content = ScheduleContent {
        seq: 1,
        network: MoneroNetwork::Regtest,
        issuer_name: ISSUER_NAME.to_string(),
        issuer_onion: test_onion("ghost/test/issuer", 443),
        constants: Constants {
            confirmations: 10,
            invoice_blocks: 720,
            grace_blocks: 2160,
            access_per_slot: 16,
            trial_per_slot: 8,
            invites_per_pack: 2,
            credits_per_free_pack: 10,
            min_claim_credits: 10,
            max_claim_credits: 50,
            early_window_hours: 24,
            capability_quota_bytes: 268_435_456,
        },
        // Three slots; slot 2 moves to another relay at week FIRST_WEEK + 10 (a week boundary).
        slots: vec![
            SlotEntry {
                slot: 0,
                onion: test_onion("ghost/test/relay-a", 443),
                valid_from_week: FIRST_WEEK,
                valid_until_week: 0,
            },
            SlotEntry {
                slot: 1,
                onion: test_onion("ghost/test/relay-b", 443),
                valid_from_week: FIRST_WEEK,
                valid_until_week: 0,
            },
            SlotEntry {
                slot: 2,
                onion: test_onion("ghost/test/relay-c", 443),
                valid_from_week: FIRST_WEEK,
                valid_until_week: FIRST_WEEK + 10,
            },
            SlotEntry {
                slot: 2,
                onion: test_onion("ghost/test/relay-d", 9001),
                valid_from_week: FIRST_WEEK + 10,
                valid_until_week: 0,
            },
        ],
        prices,
        keys,
        revoked: Vec::new(),
    };
    let key = fixture::schedule_signing_key();
    let signature = key.sign(&content.signing_message().unwrap());
    let bytes = content.to_signed_bytes(&signature.to_bytes()).unwrap();
    let schedule = Schedule::verify_with_key(&bytes, &key.verifying_key().to_bytes()).unwrap();
    assert_eq!(schedule.first_access_week(), FIRST_WEEK);
    std::fs::create_dir_all(fixture::dir()).unwrap();
    std::fs::write(fixture::dir().join("test_schedule.ghes"), &bytes).unwrap();
    std::fs::write(fixture::dir().join("test_keys.txt"), key_file).unwrap();
}

/// Seeds and ids of the [ghost] vectors: SHA-256 of a label, so they are reproducible.
pub fn label32(label: &str) -> [u8; 32] {
    Sha256::digest(label.as_bytes()).into()
}

fn sign_all(
    signers: &std::collections::BTreeMap<(Kind, u64), CheckedSigner<ReferenceSigner>>,
    layout: &Layout,
    request: &[u8],
) -> Vec<u8> {
    let mut out = Vec::with_capacity(request.len());
    for (p, b) in layout
        .positions()
        .iter()
        .zip(request.as_chunks::<AUTHENTICATOR_LEN>().0)
    {
        let signer = &signers[&(p.kind, p.epoch)];
        out.extend_from_slice(&signer.blind_sign(b).unwrap());
    }
    out
}

fn position_fields(
    out: &mut String,
    tag: &str,
    d: &batch::DerivedPosition,
    blind_sig: &[u8],
    schedule: &Schedule,
) {
    let key = schedule.key(d.position.kind, d.position.epoch).unwrap();
    let token = token::finalize_input(&key.public_key, &d.input, blind_sig, &d.inv).unwrap();
    let p = d.position;
    writeln!(out, "{tag}.kind = {:02x}", p.kind.byte()).unwrap();
    writeln!(out, "{tag}.epoch = {}", hex::encode(p.epoch.to_be_bytes())).unwrap();
    writeln!(out, "{tag}.slot = {:02x}", p.slot.unwrap_or(batch::NO_SLOT)).unwrap();
    writeln!(out, "{tag}.nonce = {}", hex::encode(d.nonce)).unwrap();
    writeln!(out, "{tag}.salt = {}", hex::encode(d.salt)).unwrap();
    writeln!(
        out,
        "{tag}.r = {}",
        hex::encode(ghost_blind_rsa::i2osp(&d.r, AUTHENTICATOR_LEN).unwrap())
    )
    .unwrap();
    writeln!(out, "{tag}.blinded = {}", hex::encode(d.blinded)).unwrap();
    writeln!(out, "{tag}.blind_sig = {}", hex::encode(blind_sig)).unwrap();
    writeln!(out, "{tag}.token = {}", hex::encode(token.as_bytes())).unwrap();
    writeln!(out, "{tag}.nullifier = {}", hex::encode(token.nullifier())).unwrap();
}

#[test]
#[ignore = "writes the [ghost] section of blind_rsa_pp2.txt from the committed fixtures"]
fn generate_ghost_vectors() {
    let schedule = fixture::schedule();
    let signers = fixture::signers(&schedule);
    let mut out = String::from("[ghost]\n");

    writeln!(
        out,
        "vector schedule the test Entitlement Schedule (tests/fixtures/test_schedule.ghes)"
    )
    .unwrap();
    writeln!(
        out,
        "schedule_key = {}",
        hex::encode(fixture::schedule_signing_key().verifying_key().to_bytes())
    )
    .unwrap();
    writeln!(out, "schedule_sha256 = {}", hex::encode(schedule.digest())).unwrap();
    writeln!(out, "issuer_name = {}", hex::encode(ISSUER_NAME)).unwrap();

    for (kind, epoch) in [
        (Kind::Access, FIRST_WEEK),
        (Kind::Invite, invite_epoch(FIRST_WEEK)),
        (Kind::Credit, credit_epoch(FIRST_WEEK)),
    ] {
        let slot = (kind == Kind::Access).then_some(2u8);
        let challenge = TokenChallenge::ghost(ISSUER_NAME, kind, epoch, slot).unwrap();
        let key = schedule.key(kind, epoch).unwrap();
        writeln!(
            out,
            "\nvector challenge-{:02x} redemption context, challenge and key of one (kind, epoch)",
            kind.byte()
        )
        .unwrap();
        writeln!(out, "kind = {:02x}", kind.byte()).unwrap();
        writeln!(out, "epoch = {}", hex::encode(epoch.to_be_bytes())).unwrap();
        writeln!(
            out,
            "slot = {}",
            slot.map_or(String::new(), |s| format!("{s:02x}"))
        )
        .unwrap();
        writeln!(
            out,
            "redemption_context = {}",
            hex::encode(redemption_context(kind, epoch))
        )
        .unwrap();
        writeln!(
            out,
            "challenge = {}",
            hex::encode(challenge.encode().unwrap())
        )
        .unwrap();
        writeln!(
            out,
            "challenge_digest = {}",
            hex::encode(challenge.digest().unwrap())
        )
        .unwrap();
        writeln!(out, "spki = {}", hex::encode(key.public_key.to_spki())).unwrap();
        writeln!(out, "key_id = {}", hex::encode(key.key_id)).unwrap();
    }

    // Permutation proof of the first access key, valid and with one byte of sigma_3 flipped.
    let pk = &schedule.key(Kind::Access, FIRST_WEEK).unwrap().public_key;
    let signer = &signers[&(Kind::Access, FIRST_WEEK)];
    let challenges = ghost_blind_rsa::permutation_proof_challenges(pk).unwrap();
    let proof: Vec<u8> = challenges
        .iter()
        .flat_map(|c| signer.blind_sign(c).unwrap())
        .collect();
    let mut tampered = proof.clone();
    tampered[3 * AUTHENTICATOR_LEN + 100] ^= 0x01;
    writeln!(
        out,
        "\nvector perm-proof permutation proof of the access key of the first week"
    )
    .unwrap();
    writeln!(out, "spki = {}", hex::encode(pk.to_spki())).unwrap();
    writeln!(out, "challenges = {}", hex::encode(challenges.concat())).unwrap();
    writeln!(out, "proof = {}", hex::encode(&proof)).unwrap();
    writeln!(out, "tampered_proof = {}", hex::encode(&tampered)).unwrap();

    // A pack paid in XMR, base week FIRST_WEEK + 8 (slot 2 changes relay inside the pack).
    let base = FIRST_WEEK + 8;
    let seed = label32("ghost/test/seed/pack");
    let invoice_id: [u8; 16] = label32("ghost/test/invoice")[..16].try_into().unwrap();
    let layout = Layout::pack(&schedule, base, true).unwrap();
    let request = batch::blind(&schedule, &seed, &layout).unwrap();
    let response = sign_all(&signers, &layout, &request);
    let tokens = batch::finalize(&schedule, &seed, &layout, &response).unwrap();
    for (t, p) in tokens.iter().zip(layout.positions()) {
        let expect = match p.kind {
            Kind::Access => Expect::AccessAtSlot(p.slot.unwrap()),
            Kind::Invite => Expect::Invite,
            Kind::Credit => Expect::Credit,
        };
        schedule.verify_token(t, expect).unwrap();
    }
    let token_bytes: Vec<u8> = tokens.iter().flat_map(|t| t.as_bytes().to_vec()).collect();
    writeln!(
        out,
        "\nvector pack-xmr pack paid in XMR: every position derived from one seed"
    )
    .unwrap();
    writeln!(out, "seed = {}", hex::encode(seed)).unwrap();
    writeln!(out, "base_week = {}", hex::encode(base.to_be_bytes())).unwrap();
    writeln!(out, "invoice_id = {}", hex::encode(invoice_id)).unwrap();
    writeln!(
        out,
        "positions = {}",
        hex::encode((layout.len() as u32).to_be_bytes())
    )
    .unwrap();
    writeln!(out, "layout_digest = {}", hex::encode(layout.digest())).unwrap();
    writeln!(
        out,
        "request_sha256 = {}",
        hex::encode(Sha256::digest(&request))
    )
    .unwrap();
    writeln!(
        out,
        "request_digest = {}",
        hex::encode(batch::request_digest(&invoice_id, &request))
    )
    .unwrap();
    writeln!(
        out,
        "response_sha256 = {}",
        hex::encode(Sha256::digest(&response))
    )
    .unwrap();
    writeln!(
        out,
        "tokens_sha256 = {}",
        hex::encode(Sha256::digest(&token_bytes))
    )
    .unwrap();
    let n = layout.len();
    for j in [0, 1, 16, 47, 48, 159, 160, n - 3, n - 2, n - 1] {
        let d = batch::derive(&schedule, &seed, &layout, j).unwrap();
        position_fields(
            &mut out,
            &format!("p{j}"),
            &d,
            &response[j * AUTHENTICATOR_LEN..(j + 1) * AUTHENTICATOR_LEN],
            &schedule,
        );
    }

    // The same base week paid with credits (no credit position) and a trial.
    let credits = Layout::pack(&schedule, base, false).unwrap();
    writeln!(
        out,
        "\nvector pack-credits pack paid with credits: layout only"
    )
    .unwrap();
    writeln!(out, "base_week = {}", hex::encode(base.to_be_bytes())).unwrap();
    writeln!(
        out,
        "positions = {}",
        hex::encode((credits.len() as u32).to_be_bytes())
    )
    .unwrap();
    writeln!(out, "layout_digest = {}", hex::encode(credits.digest())).unwrap();

    let trial_seed = label32("ghost/test/seed/trial");
    let invite_nullifier = label32("ghost/test/invite-nullifier");
    let trial = Layout::trial(&schedule, FIRST_WEEK).unwrap();
    let trial_request = batch::blind(&schedule, &trial_seed, &trial).unwrap();
    let trial_response = sign_all(&signers, &trial, &trial_request);
    writeln!(out, "\nvector trial trial of the first week").unwrap();
    writeln!(out, "seed = {}", hex::encode(trial_seed)).unwrap();
    writeln!(out, "base_week = {}", hex::encode(FIRST_WEEK.to_be_bytes())).unwrap();
    writeln!(out, "invite_nullifier = {}", hex::encode(invite_nullifier)).unwrap();
    writeln!(
        out,
        "positions = {}",
        hex::encode((trial.len() as u32).to_be_bytes())
    )
    .unwrap();
    writeln!(out, "layout_digest = {}", hex::encode(trial.digest())).unwrap();
    writeln!(
        out,
        "request_sha256 = {}",
        hex::encode(Sha256::digest(&trial_request))
    )
    .unwrap();
    writeln!(
        out,
        "trial_digest = {}",
        hex::encode(batch::trial_digest(
            &invite_nullifier,
            FIRST_WEEK,
            &trial_request
        ))
    )
    .unwrap();
    writeln!(
        out,
        "response_sha256 = {}",
        hex::encode(Sha256::digest(&trial_response))
    )
    .unwrap();
    let d = batch::derive(&schedule, &trial_seed, &trial, 0).unwrap();
    position_fields(
        &mut out,
        "p0",
        &d,
        &trial_response[..AUTHENTICATOR_LEN],
        &schedule,
    );

    // A refresh of a credit of the first credit epoch.
    let refresh = Layout::refresh(&schedule, credit_epoch(FIRST_WEEK)).unwrap();
    writeln!(out, "\nvector refresh one CREDIT position").unwrap();
    writeln!(
        out,
        "positions = {}",
        hex::encode((refresh.len() as u32).to_be_bytes())
    )
    .unwrap();
    writeln!(out, "layout_digest = {}", hex::encode(refresh.digest())).unwrap();
    assert_eq!(
        refresh.positions(),
        [Position {
            kind: Kind::Credit,
            epoch: credit_epoch(FIRST_WEEK),
            slot: None
        }]
    );

    match std::env::var("GHOST_VECTOR_OUT") {
        Ok(path) => std::fs::write(path, out).unwrap(),
        Err(_) => print!("{out}"),
    }
}
