//! Regenerates the T2 test Entitlement Schedule (Phase 8 design §13.4 "Test ES", §19.16 point 1):
//! S = 3 slots, `access_per_slot = 4`, `trial_per_slot = 2`, 64 access weeks from 2957 (the
//! 40-week warm-up, the 12-week scored window, the four weeks a last pack covers and slack), with
//! fresh RSA-2048 keys and their permutation proofs, signed with the test schedule key. The test is
//! ignored; run it only to rebuild the fixtures (every pinned T2 result changes with the keys):
//!
//!   cargo test --release -p ghost-issuer --test t2_fixture_gen -- --ignored
//!
//! Output: `tests/fixtures/t2_schedule.ghes` and `tests/fixtures/t2_keys.txt` of this crate (test
//! fixtures; never loaded by production code).

mod common;

use std::fmt::Write as _;

use common::fixture;
use ed25519_dalek::Signer as _;
use ghost_entitlement::grid::{credit_epoch, invite_epoch, price_epoch, Kind};
use ghost_entitlement::monero::MoneroNetwork;
use ghost_entitlement::onion::Onion;
use ghost_entitlement::schedule::{Constants, KeyContent, PriceEntry, ScheduleContent, SlotEntry};
use ghost_entitlement::Schedule;
use ghost_issuer::signer::{CheckedSigner, ReferenceSigner, Signer};
use sha2::{Digest, Sha256};

const FIRST_WEEK: u64 = 2957;
const WEEKS: u64 = 64;

fn onion(label: &str) -> String {
    Onion {
        pubkey: Sha256::digest(label.as_bytes()).into(),
        port: 443,
    }
    .format()
}

#[test]
#[ignore = "regenerates tests/fixtures/t2_schedule.ghes and t2_keys.txt with fresh keys"]
fn generate_t2_schedule() {
    let weeks = FIRST_WEEK..FIRST_WEEK + WEEKS;
    let mut list: Vec<(Kind, u64)> = weeks.clone().map(|w| (Kind::Access, w)).collect();
    let mut invites: Vec<u64> = weeks.clone().map(invite_epoch).collect();
    invites.dedup();
    let mut credits: Vec<u64> = weeks.clone().map(credit_epoch).collect();
    credits.dedup();
    list.extend(invites.into_iter().map(|e| (Kind::Invite, e)));
    list.extend(credits.iter().map(|&e| (Kind::Credit, e)));

    let mut keys = Vec::new();
    let mut key_file = String::from(
        "# Test-only private keys of t2_schedule.ghes: <kind byte> <epoch> <PKCS #8 DER hex>.\n\
         # Generated by issuer/crates/service/tests/t2_fixture_gen.rs; never loaded by production code.\n",
    );
    for (kind, epoch) in list {
        let signer = ReferenceSigner::generate(kind, epoch).unwrap();
        let pk = signer.public_key().clone();
        let der = signer.to_pkcs8_der().unwrap();
        let checked = CheckedSigner::new(signer, pk.clone()).unwrap();
        let challenges = ghost_blind_rsa::permutation_proof_challenges(&pk).unwrap();
        let proof = challenges.map(|c| checked.blind_sign(&c).unwrap());
        ghost_blind_rsa::verify_permutation_proof(&pk, &proof).unwrap();
        keys.push(KeyContent {
            kind,
            epoch,
            spki: pk.to_spki(),
            proof,
        });
        writeln!(key_file, "{} {} {}", kind.byte(), epoch, hex::encode(der)).unwrap();
    }
    let prices = (price_epoch(FIRST_WEEK)..=price_epoch(FIRST_WEEK + WEEKS - 1))
        .map(|e| PriceEntry {
            price_epoch: e,
            pack_price_atomic: 200_000_000_000,
        })
        .collect();
    let slots = ["a", "b", "c"]
        .iter()
        .enumerate()
        .map(|(i, l)| SlotEntry {
            slot: i as u8,
            onion: onion(&format!("ghost/t2/relay-{l}")),
            valid_from_week: FIRST_WEEK,
            valid_until_week: 0,
        })
        .collect();
    let content = ScheduleContent {
        seq: 1,
        network: MoneroNetwork::Regtest,
        issuer_name: "ghost-issuer-t2".to_string(),
        issuer_onion: onion("ghost/t2/issuer"),
        constants: Constants {
            confirmations: 10,
            invoice_blocks: 720,
            grace_blocks: 2160,
            access_per_slot: 4,
            trial_per_slot: 2,
            invites_per_pack: 2,
            credits_per_free_pack: 10,
            min_claim_credits: 10,
            max_claim_credits: 50,
            early_window_hours: 24,
            capability_quota_bytes: 268_435_456,
        },
        slots,
        prices,
        keys,
        revoked: Vec::new(),
    };
    let key = fixture::schedule_signing_key();
    let signature = key.sign(&content.signing_message().unwrap());
    let bytes = content.to_signed_bytes(&signature.to_bytes()).unwrap();
    let schedule = Schedule::verify_with_key(&bytes, &key.verifying_key().to_bytes()).unwrap();
    assert_eq!(schedule.first_access_week(), FIRST_WEEK);
    assert_eq!(schedule.last_access_week(), FIRST_WEEK + WEEKS - 1);
    let dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    std::fs::create_dir_all(&dir).unwrap();
    std::fs::write(dir.join("t2_schedule.ghes"), &bytes).unwrap();
    std::fs::write(dir.join("t2_keys.txt"), key_file).unwrap();
}
