//! The committed ops fixtures (`tests/fixtures`: the source of the test schedule and its sealed
//! test keys) and the fixture roots of `scripts/gates/entitlement-schedule.sh`
//! (`test-harness/gates/entitlement-schedule`). Everything derived deterministically is checked
//! byte for byte; the two ignored tests regenerate the files:
//!
//!   cargo test -p ghost-issuer-ops --test fixtures_check -- --ignored write_ops_fixtures
//!   cargo test -p ghost-issuer-ops --test fixtures_check -- --ignored write_gate_fixtures
//!
//! (the gate fixtures copy one sealed key, so write the ops fixtures first).

mod common;

use std::fmt::Write as _;
use std::path::PathBuf;

use common::*;
use ghost_entitlement::schedule::{ScheduleContent, SlotEntry};
use ghost_entitlement::Kind;
use ghost_issuer::custody::{self, kind_name, CustodySecret};
use ghost_issuer::signer::CheckedSigner;
use ghost_issuer_ops::report;
use ring::rand::SystemRandom;

/// The schedule source that reproduces `content` (without its keys' material).
fn source_for(content: &ScheduleContent) -> String {
    let c = &content.constants;
    let mut out = String::from(
        "# Source of the test Entitlement Schedule of ghost-entitlement (test_schedule.ghes):\n\
         # ghost-issuer-ops schedule-sign with the test schedule key reproduces it byte for byte.\n\
         # Test schedules only. Generated by issuer/crates/ops/tests/fixtures_check.rs.\n",
    );
    writeln!(out, "seq {}", content.seq).unwrap();
    writeln!(out, "network {}", report::network_name(content.network)).unwrap();
    writeln!(out, "issuer_name {}", content.issuer_name).unwrap();
    writeln!(out, "issuer_onion {}", content.issuer_onion).unwrap();
    for (name, value) in [
        ("confirmations", u64::from(c.confirmations)),
        ("invoice_blocks", u64::from(c.invoice_blocks)),
        ("grace_blocks", u64::from(c.grace_blocks)),
        ("access_per_slot", u64::from(c.access_per_slot)),
        ("trial_per_slot", u64::from(c.trial_per_slot)),
        ("invites_per_pack", u64::from(c.invites_per_pack)),
        ("credits_per_free_pack", u64::from(c.credits_per_free_pack)),
        ("min_claim_credits", u64::from(c.min_claim_credits)),
        ("max_claim_credits", u64::from(c.max_claim_credits)),
        ("early_window_hours", u64::from(c.early_window_hours)),
        ("capability_quota_bytes", c.capability_quota_bytes),
    ] {
        writeln!(out, "{name} {value}").unwrap();
    }
    for s in &content.slots {
        writeln!(
            out,
            "slot {} {} {} {}",
            s.slot, s.onion, s.valid_from_week, s.valid_until_week
        )
        .unwrap();
    }
    for p in &content.prices {
        writeln!(out, "price {} {}", p.price_epoch, p.pack_price_atomic).unwrap();
    }
    // Runs of consecutive epochs of one kind, in schedule order.
    let mut runs: Vec<(Kind, u64, u64)> = Vec::new();
    for k in &content.keys {
        match runs.last_mut() {
            Some((kind, _, last)) if *kind == k.kind && k.epoch == *last + 1 => *last = k.epoch,
            _ => runs.push((k.kind, k.epoch, k.epoch)),
        }
    }
    for (kind, first, last) in runs {
        writeln!(out, "keys {} {first} {last}", kind_name(kind)).unwrap();
    }
    for (kind, epoch) in &content.revoked {
        writeln!(out, "revoke {} {epoch}", kind_name(*kind)).unwrap();
    }
    out
}

/// Unix instant used by the gate self-test for the relay directory check: week 2960, 01:00 UTC.
pub const GATE_NOW: u64 = 1_790_557_200;

fn with_slot_3(from_week: u64) -> Vec<u8> {
    let mut c = test_content();
    c.seq = 2;
    c.slots.push(SlotEntry {
        slot: 3,
        onion: onion("ghost/test/relay-e", 443),
        valid_from_week: from_week,
        valid_until_week: 0,
    });
    resign(&c)
}

/// Every generated file of the gate's fixture roots with its bytes.
fn gate_files() -> Vec<(PathBuf, Vec<u8>)> {
    let root = gate_fixtures();
    let es = |case: &str| root.join(case).join("protocol/entitlement/schedule.ghes");
    let dir = |case: &str| {
        root.join(case)
            .join("protocol/entitlement/relay-directory.txt")
    };
    let relays = |ops: [u8; 5]| {
        directory_text(
            &[
                "ghost/test/relay-a",
                "ghost/test/relay-b",
                "ghost/test/relay-c",
                "ghost/test/relay-d",
                "ghost/test/relay-e",
            ]
            .into_iter()
            .zip(ops)
            .collect::<Vec<_>>(),
        )
        .into_bytes()
    };
    let positive = with_slot_3(LAST_WEEK + 1);
    let mut tampered = positive.clone();
    tampered[200] ^= 0x01;
    let mut duplicated = test_content();
    duplicated.keys[1].spki = duplicated.keys[0].spki.clone();
    duplicated.keys[1].proof = duplicated.keys[0].proof;
    let ok = relays([1, 1, 2, 2, 2]);
    let mut missing_c = String::from_utf8(ok.clone()).unwrap();
    let c = onion("ghost/test/relay-c", 443);
    missing_c = missing_c
        .lines()
        .filter(|l| !l.contains(&c))
        .map(|l| format!("{l}\n"))
        .collect();
    vec![
        (es("positive"), positive.clone()),
        (dir("positive"), ok.clone()),
        (es("tampered"), tampered),
        (dir("tampered"), ok.clone()),
        (es("slot-set-changed"), with_slot_3(2970)),
        (dir("slot-set-changed"), ok.clone()),
        (es("duplicated-key"), resign(&duplicated)),
        (dir("duplicated-key"), ok.clone()),
        (es("directory-missing-onion"), positive.clone()),
        (dir("directory-missing-onion"), missing_c.into_bytes()),
        (es("directory-single-operator"), positive.clone()),
        (dir("directory-single-operator"), relays([1; 5])),
        (es("directory-absent"), positive.clone()),
        (root.join("second-copy/infra/relay/schedule.ghes"), positive),
        (
            root.join("sealed-key-committed/infra/issuer/access-2957.ghks"),
            std::fs::read(ops_fixtures().join("sealed/access-2957.ghks")).unwrap(),
        ),
    ]
}

#[test]
fn committed_source_reproduces_the_test_schedule_source() {
    let committed = std::fs::read_to_string(ops_fixtures().join("test_schedule.source")).unwrap();
    assert_eq!(committed, source_for(&test_content()));
}

#[test]
fn committed_sealed_test_keys_open_into_the_test_keys() {
    let secret = CustodySecret::from_bytes(custody_seed());
    let schedule = test_schedule();
    let keys = test_keys();
    assert_eq!(keys.len(), 36);
    for (kind, epoch, der) in keys {
        let sealed = std::fs::read(
            ops_fixtures()
                .join("sealed")
                .join(custody::sealed_file_name(kind, epoch)),
        )
        .unwrap();
        let signer = custody::unseal(&secret.seal_key(kind, epoch), kind, epoch, &sealed).unwrap();
        assert_eq!(signer.to_pkcs8_der().unwrap(), der);
        let es_key = schedule.key(kind, epoch).unwrap().public_key.clone();
        assert!(CheckedSigner::new(signer, es_key).is_ok());
    }
    let files = std::fs::read_dir(ops_fixtures().join("sealed"))
        .unwrap()
        .count();
    assert_eq!(files, 36);
}

#[test]
fn gate_fixtures_are_reproducible() {
    for (path, bytes) in gate_files() {
        let committed = std::fs::read(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        assert!(
            committed == bytes,
            "{} differs (write_gate_fixtures)",
            path.display()
        );
    }
    // The instant the self-test passes lies in week 2960.
    assert_eq!(ghost_entitlement::grid::week(GATE_NOW), 2960);
}

#[test]
#[ignore = "rewrites issuer/crates/ops/tests/fixtures (sealed files get fresh nonces)"]
fn write_ops_fixtures() {
    std::fs::write(
        ops_fixtures().join("test_schedule.source"),
        source_for(&test_content()),
    )
    .unwrap();
    let sealed_dir = ops_fixtures().join("sealed");
    std::fs::create_dir_all(&sealed_dir).unwrap();
    let secret = CustodySecret::from_bytes(custody_seed());
    let rng = SystemRandom::new();
    for (kind, epoch, der) in test_keys() {
        let sealed = custody::seal(&secret.seal_key(kind, epoch), kind, epoch, &der, &rng).unwrap();
        std::fs::write(
            sealed_dir.join(custody::sealed_file_name(kind, epoch)),
            sealed,
        )
        .unwrap();
    }
}

#[test]
#[ignore = "rewrites the generated files under test-harness/gates/entitlement-schedule"]
fn write_gate_fixtures() {
    for (path, bytes) in gate_files() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, bytes).unwrap();
    }
}
