//! `onion-keygen` (design §19.10 point 3, §19.17 point 1): the files are C Tor's
//! `HiddenServiceDir` key set. Checked against RFC 8032 (the expanded key signs the published
//! vector), Arti's reader of C Tor's expanded secret key, a key set generated by C Tor (shipped in
//! `tor-keymgr` 0.46.0 `testdata/tor-service`, public files only here), the client's onion address
//! parser and the Entitlement Schedule's.

mod common;

use std::path::Path;

use common::*;
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use ghost_client_net::OnionAddress;
use ghost_entitlement::onion::{self, Onion};
use ghost_issuer_ops::onion_keygen::{self, KeySet, FILES, HEADER_LEN};
use ghost_issuer_ops::report::{Code, Field, Value};
use ghost_issuer_ops::Status;
use sha2::{Digest, Sha512};
use tor_llcrypto::pk::ed25519::ExpandedKeypair;

/// RFC 8032 §7.1 TEST 1: secret key (seed), public key, and the signature of the empty message.
const RFC8032_SEED: &str = "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60";
const RFC8032_PUBLIC: &str = "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a";
const RFC8032_SIGNATURE: &str = "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b";

/// `tor-keymgr` 0.46.0 `testdata/tor-service`, written by C Tor: `hs_ed25519_public_key` (64
/// bytes) and `hostname` (63 bytes).
const CTOR_PUBLIC_KEY_FILE: &str = "3d3d206564323535313976312d7075626c69633a207479706530203d3d000000cd4eb1cbf39e2fd0d4a52231b22edbf986bc3b0e4a180f4a97f5239415ecb6f7";
const CTOR_HOSTNAME_FILE: &str = "zvhlds7ttyx5bvffeiy3elw37gdlyoyojima6sux6urzifpmw334cpid.onion\n";
/// The first 32 bytes of that set's `hs_ed25519_secret_key` (the header only).
const CTOR_SECRET_HEADER: &str = "3d3d206564323535313976312d7365637265743a207479706530203d3d000000";

fn seed(hex_text: &str) -> [u8; 32] {
    unhex(hex_text).try_into().unwrap()
}

fn expanded(keys: &KeySet) -> [u8; 64] {
    keys.secret_key_file[HEADER_LEN..].try_into().unwrap()
}

/// Everything a reader of the three files can check without the seed.
fn check_set(secret: &[u8], public: &[u8], hostname: &str, public_key: &[u8; 32]) {
    assert_eq!(secret.len(), 96);
    assert_eq!(&secret[..HEADER_LEN], unhex(CTOR_SECRET_HEADER).as_slice());
    assert_eq!(public.len(), 64);
    assert_eq!(
        &public[..HEADER_LEN],
        &unhex(CTOR_PUBLIC_KEY_FILE)[..HEADER_LEN]
    );
    assert_eq!(&public[HEADER_LEN..], public_key);
    // Clamped as ed25519_ref10_seckey_expand leaves it.
    assert_eq!(secret[HEADER_LEN] & 7, 0);
    assert_eq!(secret[HEADER_LEN + 31] & 0xc0, 0x40);
    // Arti's reader of C Tor's key file derives the same public key from the 64 bytes.
    let arti = ExpandedKeypair::from_secret_key_bytes(secret[HEADER_LEN..].try_into().unwrap())
        .expect("Arti loads the expanded secret key");
    assert_eq!(arti.public().to_bytes(), *public_key);
    // The host name, with Tor's newline, parses to the same key in the client and in the ES.
    assert_eq!(hostname.len(), 63);
    let host = hostname.strip_suffix('\n').expect("newline-terminated");
    assert_eq!(host, onion::hostname(public_key));
    let client = OnionAddress::parse(&format!("{host}:443")).expect("the client accepts it");
    assert_eq!(client.host(), host);
    let es = Onion::parse(&format!("{host}:443")).expect("the ES accepts it");
    assert_eq!(es.pubkey, *public_key);
    assert_eq!(es.format(), format!("{host}:443"));
}

#[test]
fn the_expanded_key_signs_the_rfc_8032_vector() {
    let keys = onion_keygen::key_set(&seed(RFC8032_SEED));
    assert_eq!(keys.public_key.to_vec(), unhex(RFC8032_PUBLIC));
    check_set(
        &keys.secret_key_file,
        &keys.public_key_file,
        &keys.hostname_file,
        &keys.public_key,
    );
    // Both halves matter: the clamped scalar and the hash prefix (the deterministic nonce) must
    // reproduce the published signature byte for byte.
    let arti = ExpandedKeypair::from_secret_key_bytes(expanded(&keys)).unwrap();
    assert_eq!(arti.sign(b"").to_bytes().to_vec(), unhex(RFC8032_SIGNATURE));
    // The expanded key is SHA-512 of the seed with only bytes 0 and 31 changed.
    let digest = Sha512::digest(seed(RFC8032_SEED));
    let e = expanded(&keys);
    assert_eq!(e[1..31], digest[1..31]);
    assert_eq!(e[32..], digest[32..]);
    assert_eq!(e[0], digest[0] & 248);
    assert_eq!(e[31], (digest[31] & 63) | 64);
    assert_eq!(format!("{keys:?}"), "KeySet(redacted)");
}

#[test]
fn host_names_match_a_key_set_written_by_c_tor() {
    let file = unhex(CTOR_PUBLIC_KEY_FILE);
    assert_eq!(&file[..HEADER_LEN], onion_keygen::public_header());
    assert_eq!(
        unhex(CTOR_SECRET_HEADER).as_slice(),
        onion_keygen::secret_header()
    );
    let public_key: [u8; 32] = file[HEADER_LEN..].try_into().unwrap();
    assert_eq!(
        format!("{}\n", onion::hostname(&public_key)),
        CTOR_HOSTNAME_FILE
    );
    let host = CTOR_HOSTNAME_FILE.trim_end();
    assert!(OnionAddress::parse(&format!("{host}:443")).is_ok());
    assert_eq!(
        Onion::parse(&format!("{host}:443")).unwrap().pubkey,
        public_key
    );
}

#[test]
fn generated_sets_sign_and_verify() {
    for label in ["a", "b", "c"] {
        let s: [u8; 32] = sha2::Sha256::digest(label.as_bytes()).into();
        let keys = onion_keygen::key_set(&s);
        check_set(
            &keys.secret_key_file,
            &keys.public_key_file,
            &keys.hostname_file,
            &keys.public_key,
        );
        let arti = ExpandedKeypair::from_secret_key_bytes(expanded(&keys)).unwrap();
        let signature = Signature::from_bytes(&arti.sign(b"ghost").to_bytes());
        VerifyingKey::from_bytes(&keys.public_key)
            .unwrap()
            .verify(b"ghost", &signature)
            .unwrap();
    }
}

fn read_set(dir: &Path) -> (Vec<u8>, Vec<u8>, String) {
    (
        std::fs::read(dir.join(onion_keygen::SECRET_KEY_FILE)).unwrap(),
        std::fs::read(dir.join(onion_keygen::PUBLIC_KEY_FILE)).unwrap(),
        std::fs::read_to_string(dir.join(onion_keygen::HOSTNAME_FILE)).unwrap(),
    )
}

#[test]
fn onion_keygen_writes_a_new_hidden_service_dir() {
    let dir = tempfile::tempdir().unwrap();
    let mut publics = Vec::new();
    for name in ["relay-a", "nested/relay-b"] {
        let hs = dir.path().join(name);
        let (status, lines) = run(&["onion-keygen", "--hs-dir", &arg(&hs)]);
        assert_eq!(status, Status::Ok, "{lines:?}");
        assert_eq!(lines.len(), 1);
        assert_eq!(lines[0].code, Code::OnionKeyCreated);
        // The report carries the public key and nothing else.
        assert_eq!(lines[0].fields.len(), 1);
        let Some(Value::Hex(public)) = field(&lines[0], Field::Public) else {
            panic!("{lines:?}");
        };
        let public_key: [u8; 32] = public.clone().try_into().unwrap();
        let (secret, public_file, hostname) = read_set(&hs);
        check_set(&secret, &public_file, &hostname, &public_key);
        let mut names: Vec<String> = std::fs::read_dir(&hs)
            .unwrap()
            .map(|e| e.unwrap().file_name().into_string().unwrap())
            .collect();
        names.sort();
        let mut expected: Vec<String> = FILES.iter().map(|f| f.to_string()).collect();
        expected.sort();
        assert_eq!(names, expected);
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = |p: &Path| std::fs::metadata(p).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode(&hs), 0o700);
            for f in FILES {
                assert_eq!(mode(&hs.join(f)), 0o600, "{f}");
            }
        }
        publics.push(public_key);
    }
    assert_ne!(publics[0], publics[1]);

    // A key set is never replaced, whichever of its files exists.
    let hs = dir.path().join("relay-a");
    let before = read_set(&hs);
    assert_refused(
        &run(&["onion-keygen", "--hs-dir", &arg(&hs)]),
        Code::IoError,
        "exists",
    );
    assert_eq!(read_set(&hs), before);
    for f in FILES {
        let partial = dir.path().join(format!("partial-{f}"));
        std::fs::create_dir_all(&partial).unwrap();
        std::fs::write(partial.join(f), b"x").unwrap();
        assert_refused(
            &run(&["onion-keygen", "--hs-dir", &arg(&partial)]),
            Code::IoError,
            "exists",
        );
        assert_eq!(std::fs::read_dir(&partial).unwrap().count(), 1, "{f}");
    }
}

#[test]
fn onion_keygen_command_lines_are_refused_by_flag_name() {
    let usage = |args: &[&str], reason: &str, flag: Option<&str>| {
        let result = run(args);
        assert_eq!(result.0, Status::Usage, "{:?}", result.1);
        assert_refused(&result, Code::Usage, reason);
        assert_eq!(word(result.1.last().unwrap(), Field::Flag), flag);
    };
    usage(&["onion-keygen"], "missing-flag", Some("hs-dir"));
    usage(&["onion-keygen", "--port", "443"], "unknown-flag", None);
    usage(
        &["onion-keygen", "--hs-dir", "a", "--hs-dir", "b"],
        "repeated-flag",
        Some("hs-dir"),
    );
    usage(
        &["onion-keygen", "--hs-dir"],
        "missing-value",
        Some("hs-dir"),
    );
}
