//! The T2 test Entitlement Schedule (`tests/fixtures/t2_schedule.ghes`, generated by
//! `t2_fixture_gen.rs`): S = 3, `access_per_slot = 4`, `trial_per_slot = 2` (N = 63 per XMR pack,
//! 12 per trial), 64 access weeks from 2957, one price for every price epoch; its private keys
//! (`t2_keys.txt`) behind the issuer's own fault check.
//!
//! **Signature cache (§19.17 point 3).** Blind signing is deterministic in (key, B), so the issuer's
//! signers in a family of worlds that share client seeds (a world and its NI-1 twin, the mutant
//! worlds on the same seeds) share one cache of `(kind, epoch, SHA-256(B)) → s'`. The issuer
//! handlers, the store, the journal and the fault check (`CheckedSigner`, `s'^e == B`) run unchanged
//! on every call; only the private-key exponentiation of a block already signed under the same key
//! is served from the cache.

use std::collections::{BTreeMap, HashMap};
use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex, OnceLock};

use ghost_entitlement::token::AUTHENTICATOR_LEN;
use ghost_entitlement::{Kind, Schedule};
use ghost_issuer::custody::KeyWindow;
use ghost_issuer::signer::{CheckedSigner, ReferenceSigner, SignError, Signer};
use sha2::{Digest, Sha256};

use crate::common::fixture;

pub fn dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

pub fn schedule_bytes() -> &'static [u8] {
    static BYTES: OnceLock<Vec<u8>> = OnceLock::new();
    BYTES.get_or_init(|| {
        std::fs::read(dir().join("t2_schedule.ghes")).expect("t2_schedule.ghes (t2_fixture_gen)")
    })
}

/// The T2 test schedule, verified under the test schedule key.
pub fn schedule() -> &'static Schedule {
    static S: OnceLock<Schedule> = OnceLock::new();
    S.get_or_init(|| {
        Schedule::verify_with_key(schedule_bytes(), &fixture::schedule_public_key()).unwrap()
    })
}

/// The private keys of the T2 schedule as PKCS #8 DER, per (kind, epoch).
fn key_ders() -> &'static BTreeMap<(Kind, u64), Vec<u8>> {
    static K: OnceLock<BTreeMap<(Kind, u64), Vec<u8>>> = OnceLock::new();
    K.get_or_init(|| {
        let text = std::fs::read_to_string(dir().join("t2_keys.txt")).expect("t2_keys.txt");
        text.lines()
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .map(|line| {
                let f: Vec<&str> = line.split(' ').collect();
                let kind = Kind::from_byte(f[0].parse().unwrap()).unwrap();
                ((kind, f[1].parse().unwrap()), hex::decode(f[2]).unwrap())
            })
            .collect()
    })
}

/// One shard of the cache: `(kind, epoch, SHA-256(B)) → s'`.
type Shard = Mutex<HashMap<(u8, u64, [u8; 32]), [u8; AUTHENTICATOR_LEN]>>;

/// `(kind, epoch, SHA-256(B)) → s'`, sharded.
#[derive(Default)]
pub struct SignCache {
    shards: [Shard; 16],
    pub hits: AtomicU64,
    pub misses: AtomicU64,
}

impl SignCache {
    pub fn new() -> Arc<Self> {
        Arc::new(Self::default())
    }
}

/// One cache for every world of the process: an entry is a deterministic function of the key and
/// the block, so worlds of any seeds may share it (worlds on the same client seeds hit it).
pub fn global_cache() -> Arc<SignCache> {
    static C: OnceLock<Arc<SignCache>> = OnceLock::new();
    Arc::clone(C.get_or_init(SignCache::new))
}

/// The reference signer of one key, served from a [`SignCache`] when the block was signed before.
pub struct CachingSigner {
    inner: ReferenceSigner,
    cache: Arc<SignCache>,
}

impl Signer for CachingSigner {
    fn key(&self) -> (Kind, u64) {
        self.inner.key()
    }

    fn blind_sign(
        &self,
        blinded: &[u8; AUTHENTICATOR_LEN],
    ) -> Result<[u8; AUTHENTICATOR_LEN], SignError> {
        let (kind, epoch) = self.inner.key();
        let digest: [u8; 32] = Sha256::digest(blinded).into();
        let key = (kind.byte(), epoch, digest);
        let shard = &self.cache.shards[usize::from(digest[0] & 15)];
        if let Some(s) = shard.lock().unwrap().get(&key) {
            self.cache.hits.fetch_add(1, Ordering::Relaxed);
            return Ok(*s);
        }
        let s = self.inner.blind_sign(blinded)?;
        self.cache.misses.fetch_add(1, Ordering::Relaxed);
        shard.lock().unwrap().insert(key, s);
        Ok(s)
    }
}

/// Every key of the T2 schedule behind its fault check, signing through `cache`.
pub fn key_window(cache: &Arc<SignCache>) -> KeyWindow {
    let s = schedule();
    let mut window = KeyWindow::new();
    for (&(kind, epoch), der) in key_ders() {
        let inner = ReferenceSigner::from_pkcs8_der(kind, epoch, der).unwrap();
        let pk = s.key(kind, epoch).unwrap().public_key.clone();
        let signer = CachingSigner {
            inner,
            cache: Arc::clone(cache),
        };
        window.insert(CheckedSigner::new(signer, pk).unwrap());
    }
    window
}

/// A plain reference signer of (kind, epoch) (mutant worlds and the budget measurement).
pub fn reference_signer(kind: Kind, epoch: u64) -> ReferenceSigner {
    ReferenceSigner::from_pkcs8_der(kind, epoch, &key_ders()[&(kind, epoch)]).unwrap()
}
